articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # Create
    path('create/', views.create, name='create'),
    #Read
    path('', views.index, name ='index'),
    path('<int:id>/', views.detail, name='detail'),
     # Update
    path('<int:id>/update/', views.update, name='update'),


     # Delete
     path('<int:id>/delete/', views.delete, name='delete'),
     
     # Comment Create
     path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
    #  'articles/10/comments/create/'
    
    # Comment Delete
    path('<int:article_id>/comments/<int:id>/delete/', views.comment_delete, name='comment_delete'),
     
]

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    # modles.Model 이라는 클래스를 상속 받아서 사용할 것이다.
     title = models.CharField(max_length=100)   
     content = models.TextField()
     created_at = models.DateTimeField(auto_now_add=True)  
     updated_at = models.DateTimeField(auto_now=True)   
    # comment_set =
    # django가 자동으로 위 코드를 추가해준다.


class Comment(models.Model):
     content = models.TextField()
     article = models.ForeignKey(Article, on_delete=models.CASCADE) # 부모가 지워졌을때, 자식이 같이 지워진다.
     # 1:N 관계에서 1은 Article, N은 Comment이다.
     
     # article_id =
     # django 가 자동으로 article_id 를 저장하고, 이 컬럼은 Article의 id를 참조한다.
     

articles/forms.py
from django.forms import ModelForm
from .models import Article, Comment

class ArticleForm(ModelForm):
    class Meta():
        model = Article
        fields = '__all__'


class CommentForm(ModelForm):
    class Meta():
        model = Comment
        # fields = '__all__'
        # fields = ('content', ) # 튜플로 해야함
        # fields => 추가할 필드 목록
                
        exclude = ('article', )
        # exclude => 제외할 필드 목록

articles/views.py
from django.shortcuts import render, redirect
from . forms import ArticleForm, CommentForm
from .models import Article, Comment
# Create your views here.

# Create 함수 만들기

def create(request):
	if request.method == 'POST':
		form = ArticleForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('articles:index')

	else: 
		form = ArticleForm()
		
	context = {
        'form': form,
	}

	return render(request, 'create.html', context)


# Read 함수 만들기
def index(request):
	articles = Article.objects.all()

	context = {
		'articles' : articles,
	}
	return render(request, 'index.html', context)

# Read (detail -> 기능 구현 (게시물 자세히 보기))
def detail(request, id):
	article = Article.objects.get(id=id) # 전체에서 하나의 article을 고르고
	comments = article.comment_set.all() # 하나의 article에 있는 모든 댓글을 가져오기
 
	form = CommentForm()

	context = {
		'article' : article,
		'form' : form,
		'comments': comments,
	}

	return render(request, 'detail.html', context)


def update(request, id):
	article = Article.objects.get(id=id) 

	if request.method == 'POST':
		form = ArticleForm(request.POST, instance=article) # 새로운 데이터 (request.POST) & 뒤는 기존 정보의 article.
		if form.is_valid():
				form.save()
				return redirect('articles:detail', id=id)
		
	else:
		form = ArticleForm(instance=article) # 기존 게시물을 폼에 넣자

	context = {
		'form' : form,
	}

	return render(request, 'update.html', context)


# Delete 함수 만들기

def delete(request, id):
       article = Article.objects.get(id=id)
       article.delete()
       
       return redirect('articles:index')
       
       
 # Comment Create 함수 만들기
def comment_create(request, article_id):
       if request.method == 'POST':
              form = CommentForm(request. POST)
              if form.is_valid():
                     comment = form.save(commit=False)
                     article = Article.objects.get(id=article_id)
                     comment.article = article
                     comment.save()
                     
                     return redirect('articles:detail', id=article_id)
       else:
              return redirect('articles:index')
       
       
# Comment Delete 함수 만들기
def comment_delete(request, article_id, id):
    comment = Comment.objects.get(id=id)
    comment.delete()
    return redirect('articles:detail', id=article_id)

articles/templates/create.html
{% extends 'base.html' %}

{% block body %}

<!-- GET요청의 Create를 다시 POST Create  => 내 자신을 호출 : GET / POST 둘다 하나의 articles/create에 위치하므로 결국 자기자신을 호출--> 
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>
{% endblock %}

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <h3>{{ article.title }}</h3>
    <p>{{ article.content }}</p>
    <p>{{ article.created_at }}</p>
    <p>{{ article.updated_at }}</p>

    <a href="{% url 'articles:update' article.id %}">update</a>
    <a href="{% url 'articles:delete' article.id %}">delete</a>

    <hr>

    <form action="{% url 'articles:comment_create' article.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="댓글 작성">
    </form>

    <hr>

    {% for comment in article.comment_set.all %}
        <li>{{ comment.content }}</li>

        <a href="{% url 'articles:comment_delete' article.id comment.id %}"> delete</a>
    {% endfor %}

{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    {% for article in articles %}
        <h3>{{article.title}}</h3>
        <a href="{% url 'articles:detail' article.id %}">detail</a>
    
    {% endfor %}

{% endblock %}

articles/templates/update.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" >
    </form>
{% endblock%}

templates/base.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
 </head>
 <body>
    {% block body %}
    {% endblock %}
 </body>
 </html>